#index:
#    path: /
#    controller: App\Controller\DefaultController::index

page01:
   path: /
   controller: App\Controller\index::aff_p1

page02:
   path: /page02
   controller: App\Controller\index::aff_p2

page03:
   path: /page03
   controller: App\Controller\index::aff_p3

page04:
   path: /page04
   controller: App\Controller\index::aff_p4
