<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKU6jhi2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKU6jhi2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKU6jhi2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKU6jhi2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKU6jhi2\App_KernelDevDebugContainer([
    'container.build_hash' => 'KU6jhi2',
    'container.build_id' => 'f8061364',
    'container.build_time' => 1629474274,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKU6jhi2');
