<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMpAdJQW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMpAdJQW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMpAdJQW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMpAdJQW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMpAdJQW\App_KernelDevDebugContainer([
    'container.build_hash' => 'MpAdJQW',
    'container.build_id' => '161a7375',
    'container.build_time' => 1627569677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMpAdJQW');
