<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH7hDeOT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7hDeOT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7hDeOT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH7hDeOT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7hDeOT\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7hDeOT',
    'container.build_id' => '056b4103',
    'container.build_time' => 1628170095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7hDeOT');
